version: "3.9"
services:
  detector:
    build:
      context: api
      dockerfile: Dockerfile.detector
    ports:
      - 8040:8080
  classifier:
    build:
      context: api
      dockerfile: Dockerfile.classifier
    ports:
      - 8041:8080